[program:tellbook-api]
directory=/home/iycodes/apps/tellbook-server
command=/home/iycodes/apps/tellbook-server/bin/tellbook-api
user=iycodes
umask=0027

autostart=true
autorestart=unexpected
startsecs=5
startretries=5
exitcodes=0
priority=20

stopsignal=TERM
stopwaitsecs=30
stopasgroup=true
killasgroup=true

environment=APP_ENV="production"

redirect_stderr=true
stdout_logfile=/var/log/supervisor/tellbook-api.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
